[tool.poetry]
name = "temp_path"
version = "0.1.0"
description = "A tool to temporarily add folders to the path."
authors = ["Jan Freyberg <jan.freyberg@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"