- include: repositories.yml
  with_items: "{{ repositories + extra_repositories }}"

- include: repository_download.yml
  with_items: "{{ download_repositories }}"

- name: import repository keys
  rpm_key:
    key: "{{ item.key }}"
    state: present
    validate_certs: "{{ item.validate_certs }}"
  with_items: "{{ rpm_key_imports }}"
  notify: clean yum cache
  retries: 3
  delay: 10
  register: result
  until: result.msg is not defined
