[tool.poetry]
name = "khaki"
version = "0.3.2"
description = "A simple Pomodoro timer using curses (and pyglet for audio playback)"
authors = ["Tarcisio Eduardo Moreira Crocomo <tarcisioe@pm.me>"]
license = "MIT"
packages = [
    { include = "khaki" },
]
readme = "README.md"
keywords = ["timer", "productivity"]

[tool.poetry.dependencies]
python = "^3.4"
pyglet = "^1.3.2"

[tool.poetry.scripts]
khaki = "khaki.__main__:run"

[tool.poetry.dev-dependencies]
pylint = "^2.2"
pylint-quotes = "^0.1.9"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
