# coding: utf-8

# flake8: noqa
"""
    (C) Copyright 2018-2019 Hewlett Packard Enterprise Development LP

    Replication

    unused  # noqa: E501

    Component version: 3.3.11-SNAPSHOT
"""


from __future__ import absolute_import

# import models into model package
from storeonce_client.v1.rep.models.bandwidth_calculator import BandwidthCalculator
from storeonce_client.v1.rep.models.bandwidth_limit import BandwidthLimit
from storeonce_client.v1.rep.models.bandwidth_limit_put_model import BandwidthLimitPutModel
from storeonce_client.v1.rep.models.bandwidth_window import BandwidthWindow
from storeonce_client.v1.rep.models.bandwidth_window_collection import BandwidthWindowCollection
from storeonce_client.v1.rep.models.bandwidth_window_put_model import BandwidthWindowPutModel
from storeonce_client.v1.rep.models.blackout_now import BlackoutNow
from storeonce_client.v1.rep.models.blackout_now_put_model import BlackoutNowPutModel
from storeonce_client.v1.rep.models.blackout_window import BlackoutWindow
from storeonce_client.v1.rep.models.blackout_window_put_model import BlackoutWindowPutModel
from storeonce_client.v1.rep.models.blackout_windows_collection import BlackoutWindowsCollection
from storeonce_client.v1.rep.models.event_filter_model import EventFilterModel
from storeonce_client.v1.rep.models.event_filters import EventFilters
from storeonce_client.v1.rep.models.event_model import EventModel
from storeonce_client.v1.rep.models.events_collection import EventsCollection
from storeonce_client.v1.rep.models.external_docs import ExternalDocs
from storeonce_client.v1.rep.models.library_mapping_slot_filter_model import LibraryMappingSlotFilterModel
from storeonce_client.v1.rep.models.library_mapping_slots_collection import LibraryMappingSlotsCollection
from storeonce_client.v1.rep.models.library_mapping_slots_model import LibraryMappingSlotsModel
from storeonce_client.v1.rep.models.library_mapping_slots_put_model import LibraryMappingSlotsPutModel
from storeonce_client.v1.rep.models.mapping_sync_counts_model import MappingSyncCountsModel
from storeonce_client.v1.rep.models.model_property import ModelProperty
from storeonce_client.v1.rep.models.nas_file_filters import NasFileFilters
from storeonce_client.v1.rep.models.nas_share_mapping import NasShareMapping
from storeonce_client.v1.rep.models.nas_share_mapping_post_model import NasShareMappingPostModel
from storeonce_client.v1.rep.models.nas_share_mapping_put_model import NasShareMappingPutModel
from storeonce_client.v1.rep.models.nas_share_mappings_collection import NasShareMappingsCollection
from storeonce_client.v1.rep.models.parametrics import Parametrics
from storeonce_client.v1.rep.models.parametrics_collection import ParametricsCollection
from storeonce_client.v1.rep.models.partner_appliance_model import PartnerApplianceModel
from storeonce_client.v1.rep.models.partner_appliance_share_model import PartnerApplianceShareModel
from storeonce_client.v1.rep.models.service_model import ServiceModel
from storeonce_client.v1.rep.models.service_put_model import ServicePutModel
from storeonce_client.v1.rep.models.share_mapping_file_filter_model import ShareMappingFileFilterModel
from storeonce_client.v1.rep.models.share_mapping_files import ShareMappingFiles
from storeonce_client.v1.rep.models.share_mapping_files_collection import ShareMappingFilesCollection
from storeonce_client.v1.rep.models.share_mapping_files_put_model import ShareMappingFilesPutModel
from storeonce_client.v1.rep.models.source_appliance import SourceAppliance
from storeonce_client.v1.rep.models.source_appliances_collection import SourceAppliancesCollection
from storeonce_client.v1.rep.models.source_library_permissions import SourceLibraryPermissions
from storeonce_client.v1.rep.models.source_library_permissions_collection import SourceLibraryPermissionsCollection
from storeonce_client.v1.rep.models.source_library_permissions_put_model import SourceLibraryPermissionsPutModel
from storeonce_client.v1.rep.models.source_permissions import SourcePermissions
from storeonce_client.v1.rep.models.source_permissions_collection import SourcePermissionsCollection
from storeonce_client.v1.rep.models.source_permissions_post_model import SourcePermissionsPostModel
from storeonce_client.v1.rep.models.source_share_permissions import SourceSharePermissions
from storeonce_client.v1.rep.models.source_share_permissions_collection import SourceSharePermissionsCollection
from storeonce_client.v1.rep.models.source_share_permissions_put_model import SourceSharePermissionsPutModel
from storeonce_client.v1.rep.models.target_appliance_model import TargetApplianceModel
from storeonce_client.v1.rep.models.target_appliance_post_model import TargetAppliancePostModel
from storeonce_client.v1.rep.models.target_appliance_put_model import TargetAppliancePutModel
from storeonce_client.v1.rep.models.target_appliances_collection import TargetAppliancesCollection
from storeonce_client.v1.rep.models.target_libraries import TargetLibraries
from storeonce_client.v1.rep.models.target_libraries_collection import TargetLibrariesCollection
from storeonce_client.v1.rep.models.target_libraries_slot import TargetLibrariesSlot
from storeonce_client.v1.rep.models.target_shares import TargetShares
from storeonce_client.v1.rep.models.target_shares_collection import TargetSharesCollection
from storeonce_client.v1.rep.models.vtl_library_default_mapping_model import VtlLibraryDefaultMappingModel
from storeonce_client.v1.rep.models.vtl_library_mapping_collection import VtlLibraryMappingCollection
from storeonce_client.v1.rep.models.vtl_library_mapping_model import VtlLibraryMappingModel
from storeonce_client.v1.rep.models.vtl_library_mapping_post_model import VtlLibraryMappingPostModel
from storeonce_client.v1.rep.models.vtl_library_mapping_put_model import VtlLibraryMappingPutModel
from storeonce_client.v1.rep.models.vtl_mapping_mapped_slots import VtlMappingMappedSlots
from storeonce_client.v1.rep.models.vtl_mapping_mapped_slots_collection import VtlMappingMappedSlotsCollection
from storeonce_client.v1.rep.models.vtl_mapping_mapped_slots_post_model import VtlMappingMappedSlotsPostModel
from storeonce_client.v1.rep.models.vtl_mapping_mapped_slots_put_model import VtlMappingMappedSlotsPutModel
from storeonce_client.v1.rep.models.vtl_slot_filters import VtlSlotFilters
from storeonce_client.v1.rep.models.window_common_model import WindowCommonModel
from storeonce_client.v1.rep.models.xml import Xml
