
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "3cf85d18684583536cd8cb3723d72028fa24abb0",
 "version": "0.10.8.a0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
