[tool.poetry]
name = "pubimport"
version = "0.3.0"
description = ""
authors = ["Dominic Looser <dominic.looser@gmail.com>"]
readme = 'README.md'

[tool.poetry.dependencies]
python = "^3.4"
click = "^7.0"
bibtexparser = "^1.1"
dominate = "^2.3"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
pubimport = 'pubimport:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
