
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-01T05:45:23-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b2990d25014aa059c200af8bb9f07d19836ff9da",
 "version": "v0.4.45"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
