---
language: python
python:
  - "3.7-dev"

sudo: required

addons:
  apt:
    packages:
    - python-pip

jobs:
  include:
    - stage: "test"
      name: "Test"
      script:
        - pip install tox
        - tox
    - stage: "publish"
      name: "Publish"
      if: tag is present
      script:
        - pip install flit
        - flit build
        - flit publish
