#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['aiohttp_metrics']

package_data = \
{'': ['*']}

install_requires = \
['aiohttp', 'prometheus_client']

extras_require = \
{'dev': ['flake8',
         'flake8-bugbear',
         'flake8-builtins-unleashed',
         'flake8-comprehensions',
         'flake8-import-order',
         'flake8-pytest',
         'flake8-print',
         'mypy'],
 'test': ['faker', 'pytest', 'pytest-aiohttp', 'coverage']}

setup(name='aiohttp_metrics',
      version='0.1.1',
      description='Prometheus metrics for aiohttp-based microservices ',
      author='Kirill Sumorokov',
      author_email='sumorokov.k@gmail.com',
      url='https://github.com/clayman74/aiohttp_metrics',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
     )
