[tool.poetry]
name = "PayPay"
version = "0.1.0"
description = ""
authors = ["Junyu Mu <me@mujunyu.com>"]

[tool.poetry.dependencies]
python = "^3.6"
paypalrestsdk = "^1.13"
wechatpy = {version = "^1.7",extras = ["cryptography"]}
python-alipay-sdk = "^1.9"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
yapf = "^0.26.0"
python-language-server = {version = "^0.22.0",extras = ["all"]}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
