[tool.poetry]
name = "radar-server"
version = "0.1.1"
description = ""
authors = ["Jared Lunde <jared@BeStellar.co>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/jaredLunde/radar-resolver"

[tool.poetry.dependencies]
python = "^3.5"
vital-tools = "^0.1.13"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
twine = "^1.13"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
