
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7f5c73877359f2a853579ed7cc1f2a3adbb2ef62",
 "version": "0.1.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
