# coding: utf-8

"""
    (C) Copyright 2018-2019 Hewlett Packard Enterprise Development LP

    Replication

    unused  # noqa: E501

    Component version: 3.3.11-SNAPSHOT
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from ..api_client import ApiClient


class SourceApplianceApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_source_appliance(self, source_appliance_id, **kwargs):  # noqa: E501
        """Get a single source appliance  # noqa: E501

        Returns the specified source appliance details  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_source_appliance(source_appliance_id, async_=True)
        >>> result = thread.get()

        :param async_ bool
        :param str source_appliance_id: Source Appliance ID (required)
        :return: SourceAppliance
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_'):
            return self.get_source_appliance_with_http_info(source_appliance_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_source_appliance_with_http_info(source_appliance_id, **kwargs)  # noqa: E501
            return data

    def get_source_appliance_with_http_info(self, source_appliance_id, **kwargs):  # noqa: E501
        """Get a single source appliance  # noqa: E501

        Returns the specified source appliance details  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_=True
        >>> thread = api.get_source_appliance_with_http_info(source_appliance_id, async_=True)
        >>> result = thread.get()

        :param async_ bool
        :param str source_appliance_id: Source Appliance ID (required)
        :return: SourceAppliance
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['source_appliance_id']  # noqa: E501
        all_params.append('async_')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_source_appliance" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'source_appliance_id' is set
        if ('source_appliance_id' not in params or
                params['source_appliance_id'] is None):
            raise ValueError("Missing the required parameter `source_appliance_id` when calling `get_source_appliance`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'source_appliance_id' in params:
            path_params['source-appliance-id'] = params['source_appliance_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/rep/source-appliances/source-appliance/{source-appliance-id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SourceAppliance',  # noqa: E501
            auth_settings=auth_settings,
            async_=params.get('async_'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_source_appliances(self, **kwargs):  # noqa: E501
        """Get all source appliances  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.get_source_appliances(async_=True)
        >>> result = thread.get()

        :param async_ bool
        :return: SourceAppliancesCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_'):
            return self.get_source_appliances_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.get_source_appliances_with_http_info(**kwargs)  # noqa: E501
            return data

    def get_source_appliances_with_http_info(self, **kwargs):  # noqa: E501
        """Get all source appliances  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_=True
        >>> thread = api.get_source_appliances_with_http_info(async_=True)
        >>> result = thread.get()

        :param async_ bool
        :return: SourceAppliancesCollection
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async_')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_source_appliances" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['BasicAuth', 'oauth']  # noqa: E501

        return self.api_client.call_api(
            '/rep/source-appliances', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='SourceAppliancesCollection',  # noqa: E501
            auth_settings=auth_settings,
            async_=params.get('async_'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
