
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "89c8a044221d564251dbbe5f3e95fce0d8f631ca",
 "version": "1.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
