- name: copy over keytab
  copy:
    src: "{{ httpd_keytab_file }}"
    dest: "/etc/nginx/conf.d/httpd.keytab"
    remote_src: "{{ httpd_ssl_keytab_files_remote_src }}"
  when: httpd_keytab_file is defined
  no_log: true
