
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-26T16:13:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "6741c622e84e0ae8068e73f5f889d53702ba3cf7",
 "version": "5.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
