
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-01T09:42:29-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0eb5ac75939f13f304c493cd657ae94171f9b016",
 "version": "v0.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
