from setuptools import setup
setup(
    name='green_bacon_sandals',
    packages=['green_bacon_sandals'],
    version='0.2',
    description='Get random image from google images',
    long_description='We made a joke in the pub about this so I made it',
    license='MIT',
    author='Sam Bass',
    author_email='sam@wirewax.com',
    url='https://github.com/atomicfruitcake/green-bacon-sandals',
    download_url='https://github.com/atomicfruitcake/green-bacon-sandals/archive/0.2.tar.gz',
    keywords=['google', 'images', 'bacon'],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 2',
        'Programming Language :: Python :: 2.6',
        'Programming Language :: Python :: 2.7',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.2',
        'Programming Language :: Python :: 3.3',
        'Programming Language :: Python :: 3.4',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
    ],
    install_requires=['apiclient'],
)
