import os

from puradouga.plugins.data import FilenameParsed

filenames = [
    os.path.join("Anime", "Conception", "Season_1", "[HorribleSubs] Conception - 09 [1080p].mkv"),
    os.path.join("Anime", "Conception", "Season_1", "[HorribleSubs] Conception - 10 [1080p].mkv"),
    os.path.join("Anime", "Conception", "Season_1", "[HorribleSubs] Conception - 11 [1080p].mkv"),
    os.path.join("Anime", "Conception", "theme-music"),
    os.path.join("Anime", "Cowboy Bebop"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 01.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 02.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 03.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 04.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 05.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 06.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 07.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 08.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 09.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 10.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 11.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 12.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 13.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 14.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 15.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 16.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 17.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 18.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 19.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 20.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 21.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 22.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 23.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 24.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 25.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "Season_1", "Cowboy Bebop 26.mkv"),
    os.path.join("Anime", "Cowboy Bebop", "theme-music"),
    os.path.join("Anime", "Darling_in_the_FranXX"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 01 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 02 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 03 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 04 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 05 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 06 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 07 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 08 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 09 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 10 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 11 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 12 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 13 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 14 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 15 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 16 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 17 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 18 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 19 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 20 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 21 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 22 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 23 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "Season_1", "[HorribleSubs] Darling in the FranXX - 24 [1080p].mkv"),
    os.path.join("Anime", "Darling_in_the_FranXX", "theme-music"),
    os.path.join("Anime", "Death_Match_kara_Hajimaru_Isekai_Kyousoukyoku"),
    os.path.join("Anime", "Detroit Metal City"),
    os.path.join("Anime", "Detroit Metal City", "Season_0"),
    os.path.join("Anime", "Detroit Metal City", "Season_0", "Detroit Metal City - Birth of a Metal Devil.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 01.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 02.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 03.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 04.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 05.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 06.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 07.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 08.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 09.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 10.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 11.mkv"),
    os.path.join("Anime", "Detroit Metal City", "Season_1", "Detroit Metal City - 12.mkv"),
    os.path.join("Anime", "Detroit Metal City", "theme-music"),
    os.path.join("Anime", "Devilman_Crybaby"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 01 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 02 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 03 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 04 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 05 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 06 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 07 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 08 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 09 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "Season_1", "[HorribleSubs] Devilman Crybaby - 10 [720p].mkv"),
    os.path.join("Anime", "Devilman_Crybaby", "theme-music"),
    os.path.join("Anime", "Devils_Line"),
    os.path.join("Anime", "Devils_Line", "Season_1"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 01 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 02 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 03 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 04 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 05 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 06 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 07 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 08 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 09 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 10 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 11 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "Season_1", "[HorribleSubs] Devils Line - 12 [1080p].mkv"),
    os.path.join("Anime", "Devils_Line", "theme-music"),
    os.path.join("Anime", "Dies_Irae"),
    os.path.join("Anime", "Dies_Irae", "Season_1"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 01 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 02 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 03 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 04 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 05 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 06 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 07 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 08 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 09 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 10 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 11 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "Season_1", "Dies Irae - 12 [1080p].mkv"),
    os.path.join("Anime", "Dies_Irae", "theme-music"),
    os.path.join("Anime", "Dorei-ku_The_Animation"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 01 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 02 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 03 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 04 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 05 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 06 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 07 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 08 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 09 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 10 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 11 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "Season_1", "[HorribleSubs] Dorei-ku The Animation - 12 [1080p].mkv"),
    os.path.join("Anime", "Dorei-ku_The_Animation", "theme-music"),
    os.path.join("Anime", "Fairy_Tail"),
    os.path.join("Anime", "Fairy_Tail", "Season_1"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 26.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 27.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 28.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 29.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 30.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 31.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 32.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 33.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 34.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 35.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 36.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 37.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 38.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 39.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 40.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 41.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 42.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 43.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 44.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 45.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 46.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 47.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_1", "FairyTail 48.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 26.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 27.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 28.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 29.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 30.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 31.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 32.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 33.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 34.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 35.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 36.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 37.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 38.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 39.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 40.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 41.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 42.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 43.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 44.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 45.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 46.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 47.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_2", "FairyTail 48.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 26.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 27.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 28.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 29.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 30.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 31.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 32.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 33.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 34.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 35.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 36.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 37.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 38.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 39.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 40.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 41.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 42.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 43.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 44.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 45.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 46.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 47.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 48.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 49.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 50.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 51.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 52.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 53.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_3", "FairyTail 54.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_4", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 26.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 27.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 28.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 29.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 30.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 31.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 32.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 33.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 34.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 35.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 36.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 37.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 38.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 39.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 40.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 41.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 42.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 43.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 44.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 45.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 46.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 47.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 48.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 49.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 50.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_5", "FairyTail 51.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 13.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 14.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 15.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 16.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 17.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 18.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 19.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 20.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 21.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 22.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 23.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 24.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 25.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 26.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 27.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 28.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 29.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 30.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 31.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 32.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 33.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 34.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 35.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 36.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 37.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 38.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_6", "FairyTail 39.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 01.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 02.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 03.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 04.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 05.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 06.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 07.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 08.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 09.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 10.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 11.mp4"),
    os.path.join("Anime", "Fairy_Tail", "Season_7", "FairyTail 12.mp4"),
    os.path.join("Anime", "Fairy_Tail", "theme-music"),
    os.path.join("Anime", "Fate_Apocrypha"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 01.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 02.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 03.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 04.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 05.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 06.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 07.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 08.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 09.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 10.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 11.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha - 12.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 13.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 14.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 15.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 16.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 17.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 18.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 19.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 20.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 21.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 22.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 23.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 24.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "Season_1", "Fate Apocrypha 25.mkv"),
    os.path.join("Anime", "Fate_Apocrypha", "theme-music"),
    os.path.join("Anime", "Fate_Extra_Last_Encore"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 01v3 [720p][F96AB377].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 02 [720p][C2E019B5].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 03 [720p][81DA8FD6].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 04 [720p][72869C2C].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 05 [720p][5EC9B549].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 06 [720p][98298F8F].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Chyuu] Fate EXTRA Last Encore - 07 [720p][50D10C86].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate EXTRA Last Encore - 08 [720p][CC0C90A1].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate EXTRA Last Encore - 09 [720p][FABE26B9].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate EXTRA Last Encore - 10 [720p][0D75646C].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate⁄EXTRA Last Encore - 11 [720p][034C22E5].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate⁄EXTRA Last Encore - 12 [720p][5AA93642].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "Season_1", "[Kooritsukai] Fate⁄EXTRA Last Encore - 13 END [720p][4FE4DAEB].mkv"),
    os.path.join("Anime", "Fate_Extra_Last_Encore", "theme-music"),
    os.path.join("Anime", "Fate_Kaleid_Prisma_Illya"),
]

media = [
    FilenameParsed(title='Conception', season='1', episode='08', source=None),
    FilenameParsed(title='Conception', season='1', episode='09', source=None),
    FilenameParsed(title='Conception', season='1', episode='10', source=None),
    FilenameParsed(title='Conception', season='1', episode='11', source=None),
    FilenameParsed(title='Conception', season=None, episode=None, source=None),
    FilenameParsed(title='Cowboy Bebop', season=None, episode=None, source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode=None, source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='01', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='02', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='03', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='04', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='05', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='06', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='07', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='08', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='09', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='10', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='11', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='12', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='13', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='14', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='15', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='16', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='17', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='18', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='19', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='20', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='21', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='22', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='23', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='24', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='25', source=None),
    FilenameParsed(title='Cowboy Bebop', season='1', episode='26', source=None),
    FilenameParsed(title='Cowboy Bebop', season=None, episode=None, source=None),
    FilenameParsed(title='Darling in the FranXX', season=None, episode=None, source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode=None, source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='01', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='02', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='03', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='04', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='05', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='06', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='07', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='08', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='09', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='10', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='11', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='12', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='13', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='14', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='15', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='16', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='17', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='18', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='19', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='20', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='21', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='22', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='23', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season='1', episode='24', source=None),
    FilenameParsed(title='DARLING in the FRANXX', season=None, episode=None, source=None),
    FilenameParsed(title='Death Match kara Hajimaru Isekai Kyousoukyoku', season=None, episode=None, source=None),
    FilenameParsed(title='Detroit Metal City', season=None, episode=None, source=None),
    FilenameParsed(title='Detroit Metal City', season='0', episode=None, source=None),
    FilenameParsed(title='Detroit Metal City', season='0', episode=None, source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode=None, source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='01', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='02', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='03', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='04', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='05', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='06', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='07', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='08', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='09', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='10', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='11', source=None),
    FilenameParsed(title='Detroit Metal City', season='1', episode='12', source=None),
    FilenameParsed(title='Detroit Metal City', season=None, episode=None, source=None),
    FilenameParsed(title='Devilman Crybaby', season=None, episode=None, source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode=None, source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='01', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='02', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='03', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='04', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='05', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='06', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='07', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='08', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='09', source=None),
    FilenameParsed(title='Devilman: Crybaby', season='1', episode='10', source=None),
    FilenameParsed(title='Devilman: Crybaby', season=None, episode=None, source=None),
    FilenameParsed(title='Devils Line', season=None, episode=None, source=None),
    FilenameParsed(title='Devils Line', season='1', episode=None, source=None),
    FilenameParsed(title='Devils Line', season='1', episode='01', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='02', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='03', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='04', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='05', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='06', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='07', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='08', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='09', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='10', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='11', source=None),
    FilenameParsed(title='Devils Line', season='1', episode='12', source=None),
    FilenameParsed(title='Devils Line', season=None, episode=None, source=None),
    FilenameParsed(title='Dies Irae', season=None, episode=None, source=None),
    FilenameParsed(title='Dies Irae', season='1', episode=None, source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='01', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='02', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='03', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='04', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='05', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='06', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='07', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='08', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='09', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='10', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='11', source=None),
    FilenameParsed(title='Dies Irae', season='1', episode='12', source=None),
    FilenameParsed(title='Dies Irae', season=None, episode=None, source=None),
    FilenameParsed(title='Dorei-ku The Animation', season=None, episode=None, source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode=None, source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='01', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='02', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='03', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='04', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='05', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='06', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='07', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='08', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='09', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='10', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='11', source=None),
    FilenameParsed(title='DOREIKU The Animation', season='1', episode='12', source=None),
    FilenameParsed(title='DOREIKU The Animation', season=None, episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season=None, episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='26', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='27', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='28', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='29', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='30', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='31', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='32', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='33', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='34', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='35', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='36', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='37', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='38', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='39', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='40', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='41', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='42', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='43', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='44', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='45', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='46', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='47', source=None),
    FilenameParsed(title='Fairy Tail', season='1', episode='48', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='26', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='27', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='28', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='29', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='30', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='31', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='32', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='33', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='34', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='35', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='36', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='37', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='38', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='39', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='40', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='41', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='42', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='43', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='44', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='45', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='46', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='47', source=None),
    FilenameParsed(title='Fairy Tail', season='2', episode='48', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='26', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='27', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='28', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='29', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='30', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='31', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='32', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='33', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='34', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='35', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='36', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='37', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='38', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='39', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='40', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='41', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='42', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='43', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='44', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='45', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='46', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='47', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='48', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='49', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='50', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='51', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='52', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='53', source=None),
    FilenameParsed(title='Fairy Tail', season='3', episode='54', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='4', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='26', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='27', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='28', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='29', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='30', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='31', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='32', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='33', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='34', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='35', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='36', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='37', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='38', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='39', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='40', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='41', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='42', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='43', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='44', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='45', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='46', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='47', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='48', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='49', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='50', source=None),
    FilenameParsed(title='Fairy Tail', season='5', episode='51', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='13', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='14', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='15', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='16', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='17', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='18', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='19', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='20', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='21', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='22', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='23', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='24', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='25', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='26', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='27', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='28', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='29', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='30', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='31', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='32', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='33', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='34', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='35', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='36', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='37', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='38', source=None),
    FilenameParsed(title='Fairy Tail', season='6', episode='39', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode=None, source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='01', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='02', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='03', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='04', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='05', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='06', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='07', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='08', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='09', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='10', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='11', source=None),
    FilenameParsed(title='Fairy Tail', season='7', episode='12', source=None),
    FilenameParsed(title='Fairy Tail', season=None, episode=None, source=None),
    FilenameParsed(title='Fate Apocrypha', season=None, episode=None, source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode=None, source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='01', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='02', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='03', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='04', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='05', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='06', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='07', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='08', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='09', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='10', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='11', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='12', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='13', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='14', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='15', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='16', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='17', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='18', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='19', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='20', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='21', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='22', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='23', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='24', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season='1', episode='25', source=None),
    FilenameParsed(title='Fate", "Apocrypha', season=None, episode=None, source=None),
    FilenameParsed(title='Fate Extra Last Encore', season=None, episode=None, source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode=None, source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='01', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='02', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='03', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='04', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='05', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='06', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='07', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='08', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='09', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='10', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='11', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='12', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season='1', episode='13', source=None),
    FilenameParsed(title='Fate", "EXTRA Last Encore', season=None, episode=None, source=None),
    FilenameParsed(title='Fate Kaleid Prisma Illya', season=None, episode=None, source=None),
]
