[tool.poetry]
name = "huey-pg"
version = "0.1.0"
description = "Postgres Broker for Huey Task Queue"
authors = ["Étienne BERSAC"]
license = "PostgreSQL"
readme = "README.rst"
include = ["huey-pg.sql"]

[tool.poetry.dependencies]
python = "^3.4"
huey = "^1.11"
psycopg2 = "^2.7"

[tool.poetry.dev-dependencies]
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
