
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-15T16:34:18+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6875c15f3f0399a0aa03cbfe91b4b2ad3c71ecb0",
 "version": "0.2.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
