pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: brewblox

steps:

- bash: |
    export TRAVIS_BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    echo ${TRAVIS_BRANCH}
    echo $(Build.SourceBranch)
    echo $(Build.SourceBranchName)
    echo $(DOCKER_USER)
    echo $(DOCKER_PASSWORD)
    echo $(PYPI_USER)
  displayName: debug env names

- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.7'
    architecture: 'x64'

- bash: |
    pip install pipenv
    pipenv sync --dev
    pipenv run pytest
  displayName: Run Pytest

# - bash: >
#     bbt-localbuild
#     --arch amd arm
#     --tags newest-tag $(git describe --tags)
#     --push
#   displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits
#   condition: and(succeeded(), )

- bash: >
    pipenv run
    bbt-localbuild
    --arch amd arm
    --branch-tag
  displayName: Deploy branch to Docker Hub on any push to the GitHub repository
