
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-28T15:32:06-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2fff71161829c8ee2d7c7f6da70a872236037bda",
 "version": "1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
