[tool.poetry]
name = "getup"
version = "0.0.20"
description = "Projectless Django setup tool"
authors = ["Jussi Arpalahti <jussi.arpalahti@gmail.com>"]
license = "MPL-2.0"
readme = 'README.md'
repository = "https://gitlab.com/jussiarpalahti/getup"

[tool.poetry.dependencies]
python = "^3.7"
django = "^2.1"
django-environ = "^0.4.5"
django-cors-headers = "^2.4"
pydantic = "^0.19.0"
dj_database_url = "^0.5.0"
email-validator = "^1.0"
dnspython = "^1.16"


[tool.poetry.dev-dependencies]
pytest = "^3.0"
black = { version = "*", allows-prereleases = true }

[tool.poetry.scripts]
getup = "getup.up:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

