conditions: v1
dist: trusty
sudo: false
language: python

python:
- 3.6

install:
- skip  # TODO: install test dependencies

script:
- skip  # TODO: run pytest

jobs:
  include:
  - python: 3.7
    dist: xenial
    sudo: true

  - stage: &stage_deploy_name upload new version of python package to PYPI (only for tagged commits)
    if: tag IS present
    python: 3.6
    install: skip
    script: skip
    deploy:
      provider: pypi
      on:
        all_branches: true
        tags: true
      user: webknjaz
      password:
        secure: mEXMK0ozwwDaluhfcKsrd7gSkyWXnAlWv33dhj2LfhX2Vvz2NaTMR6qFlGmlwnTQjIqwizk79eedIiKAnTW56Z5nUOz4udgBd8QjlHHHtcJX8AG0jagtJwGm14uAb016TmERcaNm/bPBbD/XV0cIcNf3BgyZmyVL+YJNzlEoMAC89uMHKMbxH+GxwG7Qa965re5XtTS4zdiWkM/DUgAlQcL3kro8zh1szWFFzIQpldkYsafJZX4lLJu9XI7SixmzK1AjaKFstmWfjs6WhnaLdWch/Vv1oWEspjoniaDcnZLOl3/C6zWCUBKdqLuYqubCG2ZfyByLVT+F3kFXbGiJH3KJNfLG68ndVkzMtOUzqQwaKOyu0pbeMfwMfRGf7VRBEsP/lhx74UYGn6OBtVBCH1lmJMdST9Wejdar1HFIu8uTjydd3rA4vgpnJMS27ZGjvtOcKVEbgmgLkBEMiUV7pFIg1cLg5jzUrH9wpfi9Wf3PK0ulLpKG9A+lDSddn8YfgE/aj9z5p1GJKWk+9vJ6+i3f4SzxmmlCkaLRIiLLbQGdBgylYLk2dSc0myYRr8+8j2ud3VRzYvSVXMuAsm6Snkzm/V14J6BpkkSg/XA+voBnTd2xEcI2Qd7tPyl6jOFzjRlnsXpkdFPRtJFvYisM55n5x69BmMVLZZrZk97ru2A=
      distributions: clean --all sdist bdist_wheel
      skip_cleanup: true
      skip_upload_docs: true

cache:
  pip: true
