
language: python

matrix:
  include:

# Python 3.3 can not be used with setuptools >= 36.0.0

    - python: "3.4"

    - python: "3.5"

    - python: "3.6"

    - dist: xenial
      python: "3.7"

    - python: "pypy3.5"

install:
  - pip install -r requirements.txt
  - pip install -v .

script:
  - python ./setup.py test
