apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlflow 
  labels:
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: docker.io/pipelineai/mlflow:1.5.0
        imagePullPolicy: "Always"
        terminationMessagePolicy: "FallbackToLogsOnError"
        resources:
          limits:
            memory: 1Gi
            cpu: 200m
          requests:
            memory: 1Gi
            cpu: 200m
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: users-volume
          mountPath: /mnt/pipelineai/users
      volumes:
#      - name: users-volume
#        hostPath:
#          path: /mnt/pipelineai/users
#          type: DirectoryOrCreate
      - name: users-volume
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: pipelineai-fs # name of the filesystem specified in the filesystem CRD.
            clusterNamespace: default # namespace where the Rook cluster is deployed
            # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
            # the path must exist on the filesystem, otherwise mounting the filesystem at that path will fail
            path: users/
