- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - publish-openstack-sphinx-docs
      - check-requirements
      - lib-forward-testing
      - release-notes-jobs
    check:
      jobs:
        - openstack-tox-pylint:
            voting: false
    post:
      jobs:
        - openstack-tox-cover
