[tool.poetry]
name = "specify"
version = "0.0.1"
description = "A spec tool to describe your classes"
authors = ["Einenlum <yann.rabiller@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
prophepy = ">=0.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
