# Generated by Django 2.1.5 on 2019-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wrd", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="episode",
            name="application_path",
            field=models.CharField(
                help_text="Pfad in Dropbox zu Anmeldungen, z.B. /WRD 2019/Anmeldungen/Hauptsaison",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="certificate_path",
            field=models.CharField(
                help_text="Pfad in Dropbox zu Nachweisen, z.B. /WRD 2019/Nachweise",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="guard_order_path",
            field=models.CharField(
                help_text="Pfad in Dropbox zu Wachaufträgen, z.B. /WRD 2019/Wachaufträge/1 Vorsaison",
                max_length=100,
                null=True,
            ),
        ),
    ]
