# Generated by Django 2.1.5 on 2019-01-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("wrd", "0004_auto_20190131_1739")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_status",
            field=models.IntegerField(
                choices=[
                    (0, "🌥 Interesse"),
                    (1, "🌤 Angemeldet"),
                    (3, "☀️ Wachauftrag liegt vor"),
                ],
                default=0,
            ),
        )
    ]
