- name: clean yum cache
  file:
    dest: /var/cache/{{ ansible_pkg_mgr }}
    state: absent

- name: recreate cache dir
  file:
    dest: /var/cache/{{ ansible_pkg_mgr }}
    state: directory
    owner: root
    group: root
    mode: 0755

- name: copy in shell script
  template:
    src: "{{ item }}"
    dest: /usr/local/bin
    mode: 0755
    owner: root
    group: root
  with_items: "{{ container_bin_files }}"

- name: state config file
  stat:
    path: /etc/sysconfig/jenkins_swarm.templated
  register: template_file

- name: create config file
  file:
    dest: /etc/sysconfig/jenkins_swarm.templated
    owner: "{{ jenkins_user }}"
    mode: 0644
    state: touch
  when: not template_file.stat.exists

- name: delete weird file
  file:
    dest: /var/log/lastlog
    state: absent
