[tool.poetry]
name = "taxbill"
version = "0.1.2"
description = "Tax calculator and optimiser for UK freelancers"
authors = ["Owen Campbell"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = "^3.6"
pulp = "^1.6"
click = "^7.0"
pyyaml = "^3.13"

[tool.poetry.dev-dependencies]
bumpversion = "^0.5.3"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.poetry.scripts]
taxbill = "taxbill.cli:taxbill"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
