# coding: utf-8

"""
    (C) Copyright 2018-2019 Hewlett Packard Enterprise Development LP

    Catalyst

    unused  # noqa: E501

    Component version: 10.3.15-SNAPSHOT
"""


import pprint
import re  # noqa: F401

import six


class CofcDevice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'device_name': 'str',
        'fc_address': 'str',
        'wwpn': 'str',
        'wwnn': 'str',
        'num_logins': 'int',
        'num_luns': 'int',
        'fc_device_status_info': 'int',
        'fc_device_status_info_string': 'str',
        'fc_device_status': 'int',
        'fc_device_status_string': 'str'
    }

    attribute_map = {
        'id': 'id',
        'device_name': 'deviceName',
        'fc_address': 'fcAddress',
        'wwpn': 'wwpn',
        'wwnn': 'wwnn',
        'num_logins': 'numLogins',
        'num_luns': 'numLuns',
        'fc_device_status_info': 'fcDeviceStatusInfo',
        'fc_device_status_info_string': 'fcDeviceStatusInfoString',
        'fc_device_status': 'fcDeviceStatus',
        'fc_device_status_string': 'fcDeviceStatusString'
    }

    def __init__(self, id=None, device_name=None, fc_address=None, wwpn=None, wwnn=None, num_logins=None, num_luns=None, fc_device_status_info=None, fc_device_status_info_string=None, fc_device_status=None, fc_device_status_string=None):  # noqa: E501
        """CofcDevice - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._device_name = None
        self._fc_address = None
        self._wwpn = None
        self._wwnn = None
        self._num_logins = None
        self._num_luns = None
        self._fc_device_status_info = None
        self._fc_device_status_info_string = None
        self._fc_device_status = None
        self._fc_device_status_string = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if device_name is not None:
            self.device_name = device_name
        if fc_address is not None:
            self.fc_address = fc_address
        if wwpn is not None:
            self.wwpn = wwpn
        if wwnn is not None:
            self.wwnn = wwnn
        if num_logins is not None:
            self.num_logins = num_logins
        if num_luns is not None:
            self.num_luns = num_luns
        if fc_device_status_info is not None:
            self.fc_device_status_info = fc_device_status_info
        if fc_device_status_info_string is not None:
            self.fc_device_status_info_string = fc_device_status_info_string
        if fc_device_status is not None:
            self.fc_device_status = fc_device_status
        if fc_device_status_string is not None:
            self.fc_device_status_string = fc_device_status_string

    @property
    def id(self):
        """Gets the id of this CofcDevice.  # noqa: E501

        ID of the CoFC Device  # noqa: E501

        :return: The id of this CofcDevice.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CofcDevice.

        ID of the CoFC Device  # noqa: E501

        :param id: The id of this CofcDevice.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def device_name(self):
        """Gets the device_name of this CofcDevice.  # noqa: E501

        Name of the CoFC device  # noqa: E501

        :return: The device_name of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._device_name

    @device_name.setter
    def device_name(self, device_name):
        """Sets the device_name of this CofcDevice.

        Name of the CoFC device  # noqa: E501

        :param device_name: The device_name of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._device_name = device_name

    @property
    def fc_address(self):
        """Gets the fc_address of this CofcDevice.  # noqa: E501

        Fibre channel address of the CoFC Device  # noqa: E501

        :return: The fc_address of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._fc_address

    @fc_address.setter
    def fc_address(self, fc_address):
        """Sets the fc_address of this CofcDevice.

        Fibre channel address of the CoFC Device  # noqa: E501

        :param fc_address: The fc_address of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._fc_address = fc_address

    @property
    def wwpn(self):
        """Gets the wwpn of this CofcDevice.  # noqa: E501

        World wide port name of the CoFC Device  # noqa: E501

        :return: The wwpn of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._wwpn

    @wwpn.setter
    def wwpn(self, wwpn):
        """Sets the wwpn of this CofcDevice.

        World wide port name of the CoFC Device  # noqa: E501

        :param wwpn: The wwpn of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._wwpn = wwpn

    @property
    def wwnn(self):
        """Gets the wwnn of this CofcDevice.  # noqa: E501

        World wide node name of the CoFC Device  # noqa: E501

        :return: The wwnn of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._wwnn

    @wwnn.setter
    def wwnn(self, wwnn):
        """Sets the wwnn of this CofcDevice.

        World wide node name of the CoFC Device  # noqa: E501

        :param wwnn: The wwnn of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._wwnn = wwnn

    @property
    def num_logins(self):
        """Gets the num_logins of this CofcDevice.  # noqa: E501

        Number of logins for the CoFC Device  # noqa: E501

        :return: The num_logins of this CofcDevice.  # noqa: E501
        :rtype: int
        """
        return self._num_logins

    @num_logins.setter
    def num_logins(self, num_logins):
        """Sets the num_logins of this CofcDevice.

        Number of logins for the CoFC Device  # noqa: E501

        :param num_logins: The num_logins of this CofcDevice.  # noqa: E501
        :type: int
        """

        self._num_logins = num_logins

    @property
    def num_luns(self):
        """Gets the num_luns of this CofcDevice.  # noqa: E501

        Number of Logical Unit Numbers the device presents  # noqa: E501

        :return: The num_luns of this CofcDevice.  # noqa: E501
        :rtype: int
        """
        return self._num_luns

    @num_luns.setter
    def num_luns(self, num_luns):
        """Sets the num_luns of this CofcDevice.

        Number of Logical Unit Numbers the device presents  # noqa: E501

        :param num_luns: The num_luns of this CofcDevice.  # noqa: E501
        :type: int
        """

        self._num_luns = num_luns

    @property
    def fc_device_status_info(self):
        """Gets the fc_device_status_info of this CofcDevice.  # noqa: E501

        Reason fcAddress was not acquired. Only returned when fcAddress not acquired  # noqa: E501

        :return: The fc_device_status_info of this CofcDevice.  # noqa: E501
        :rtype: int
        """
        return self._fc_device_status_info

    @fc_device_status_info.setter
    def fc_device_status_info(self, fc_device_status_info):
        """Sets the fc_device_status_info of this CofcDevice.

        Reason fcAddress was not acquired. Only returned when fcAddress not acquired  # noqa: E501

        :param fc_device_status_info: The fc_device_status_info of this CofcDevice.  # noqa: E501
        :type: int
        """

        self._fc_device_status_info = fc_device_status_info

    @property
    def fc_device_status_info_string(self):
        """Gets the fc_device_status_info_string of this CofcDevice.  # noqa: E501

        Localised string representing the device status info  # noqa: E501

        :return: The fc_device_status_info_string of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._fc_device_status_info_string

    @fc_device_status_info_string.setter
    def fc_device_status_info_string(self, fc_device_status_info_string):
        """Sets the fc_device_status_info_string of this CofcDevice.

        Localised string representing the device status info  # noqa: E501

        :param fc_device_status_info_string: The fc_device_status_info_string of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._fc_device_status_info_string = fc_device_status_info_string

    @property
    def fc_device_status(self):
        """Gets the fc_device_status of this CofcDevice.  # noqa: E501

        Current status of the CoFC Device  # noqa: E501

        :return: The fc_device_status of this CofcDevice.  # noqa: E501
        :rtype: int
        """
        return self._fc_device_status

    @fc_device_status.setter
    def fc_device_status(self, fc_device_status):
        """Sets the fc_device_status of this CofcDevice.

        Current status of the CoFC Device  # noqa: E501

        :param fc_device_status: The fc_device_status of this CofcDevice.  # noqa: E501
        :type: int
        """

        self._fc_device_status = fc_device_status

    @property
    def fc_device_status_string(self):
        """Gets the fc_device_status_string of this CofcDevice.  # noqa: E501

        Localised string representing the device status  # noqa: E501

        :return: The fc_device_status_string of this CofcDevice.  # noqa: E501
        :rtype: str
        """
        return self._fc_device_status_string

    @fc_device_status_string.setter
    def fc_device_status_string(self, fc_device_status_string):
        """Sets the fc_device_status_string of this CofcDevice.

        Localised string representing the device status  # noqa: E501

        :param fc_device_status_string: The fc_device_status_string of this CofcDevice.  # noqa: E501
        :type: str
        """

        self._fc_device_status_string = fc_device_status_string

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CofcDevice, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CofcDevice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
