sudo: false
language: python
branches:
  except: [cookiecutter]
cache: pip
jobs:
  include:
  - {stage: check, python: '3.5', env: TOX_ENV=setup}
  - {stage: check, python: '3.5', env: TOX_ENV=safety}
  - {stage: check, python: '3.5', env: TOX_ENV=style}
  - {stage: check, python: '3.5', env: TOX_ENV=docs}
  - {stage: check, python: '3.5', env: TOX_ENV=spell}
  - {stage: check, python: '3.5', env: TOX_ENV=link}
  - {stage: test, after_success: 'tox -e codacy', python: '2.7', env: TOX_ENV=py27-django18}
  - {stage: test, after_success: 'tox -e codacy', python: '2.7', env: TOX_ENV=py27-django19}
  - {stage: test, after_success: 'tox -e codacy', python: '2.7', env: TOX_ENV=py27-django110}
  - {stage: test, after_success: 'tox -e codacy', python: '2.7', env: TOX_ENV=py27-django111}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django18}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django19}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django110}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django111}
  - {stage: test, after_success: 'tox -e codacy', python: '3.5', env: TOX_ENV=py35-django20}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django18}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django19}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django110}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django111}
  - {stage: test, after_success: 'tox -e codacy', python: '3.6', env: TOX_ENV=py36-django20}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev-django18}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev-django19}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev-django110}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev-django111}
  - {stage: test, after_success: 'tox -e codacy', python: 3.7-dev, env: TOX_ENV=py37-dev-django20}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django18}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django19}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django110}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django111}
  - {stage: test, after_success: 'tox -e codacy', python: pypy, env: TOX_ENV=pypy-django20}
  fast_finish: true
  allow_failures:
  - {stage: check, env: TOX_ENV=style}
  - {stage: check, env: TOX_ENV=spell}
  - {stage: check, env: TOX_ENV=link}
  - {stage: test, env: TOX_ENV=py27-django18}
  - {stage: test, env: TOX_ENV=py34-django18}
  - {stage: test, env: TOX_ENV=py35-django18}
  - {stage: test, env: TOX_ENV=py36-django18}
  - {stage: test, env: TOX_ENV=py37-dev-django18}
  - {stage: test, env: TOX_ENV=pypy-django18}
  - {stage: test, python: 3.7-dev}
  - {stage: test, python: pypy}
addons:
  apt:
    packages: [libenchant-dev]
install: [pip install -r requirements/ci.txt]
script: ['tox -e ${TOX_ENV}']
