- name: install ntp
  become: true
  package:
    name: ntp
    state: present
  retries: 2
  register: install_ntp
  until: install_ntp is success

- name: override ntp servers when ntp_servers is defined
  block:
    - name: remove existing ntp server values
      lineinfile:
        backup: true
        dest: /etc/ntp.conf
        state: absent
        regexp: "^server"

    - name: add customized ntp servers
      blockinfile:
        dest: /etc/ntp.conf
        insertafter: EOF
        block: "{{ item }}"
      with_items: "{{ ntp_servers }}"
  when: ntp_servers is defined

- name: start the NTP service
  become: true
  service:
    name: ntpd
    state: started
    enabled: true
