---
- name: "destroy network"
  virt_net:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    command: destroy
    uri: "{{ res_def['uri'] | default('qemu:///system') }}"
  ignore_errors: yes

- name: "undefine network"
  virt_net:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    command: undefine
    uri: "{{ res_def['uri'] | default('qemu:///system') }}"
  ignore_errors: yes
