
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-25T13:11:27+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "de01d77a021e79cd993d3dce69dfe52de181b92d",
 "version": "v0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
