[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "solid_toolbox"
version = "0.0.5"
description = "A collection of utilities for solidpython"

license = "MIT"
readme = "README.md"

authors = [
    "Michael Lee <michael.lee.0x2a@gmail.com>",
]

repository = "https://github.com/michael0x2a/solid_toolbox"
homepage = "https://github.com/michael0x2a/solid_toolbox"

[tool.poetry.dependencies]
python = "^3.6"
solidpython = "^0.2.0"
click = "^7.0"
prettytable = "0.7.2"

[tool.poetry.dev-dependencies]
pytest = "^4.1.0"
flake8 = "^3.6"
black = { version="18.9-beta.0", python = "^3.6" }

[tool.black]
py36 = true
