language: python
dist: trusty
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - "pip install ."
env:
  - MODEL_TECH=dummy_value
script:
  - "fusesoc init -y"
  - "fusesoc list-cores"
  - "fusesoc update"
  - "py.test"
