[tool.poetry]
name = "red-connector-sshfs"
version = "0.2"
authors = ["Bruno Schilling <s0555131@htw-berlin.de>", "Christoph Jansen <Christoph.Jansen@htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-sshfs"
homepage = "https://curious-containers.github.io/"
description = "RED Connector SSHFS is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
jsonschema = "^2.6"
cc-connector-cli = "^0.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-sshfs = 'red_connector_sshfs.main:main'
