# The Java version to install. Older versions are deprecated and will not be
# supported beyond the EOL support for their packages in the distribution of
# choice
java_version: 8
# Optionally set the 'jenkins' Unix account UID here.  This should not normally
# need to be changed, but for certain OpenShift instances a value of
# '1000090000' is recommended.
#jenkins_user_uid: 1000090000

# Set the default (empty) set of authorized SSH public keys for jenkins user.
# To add authorized keys, override this value by adding a list of paths
# (relative or full) to files containing separate public keys.
# e.g.: ['mykey.pub', 'otherkey.pub']
jenkins_authorized_keys: []
# A list of additional packages that you wish to install on both masters and
# slaves using the default package manager.
extra_rpms: []
# The name of the RPM that includes pip
python_pip_package: python2-pip
