server:
  listen_host: 127.0.0.1
  listen_port: 5000
  server_url: http://localhost:5000

morpfw:
  scan:
    - {{ cookiecutter.project_name }}

application:
  title: {{ cookiecutter.project_name }}
  app: {{ cookiecutter.project_name }}.app:App
  dburi: 'sqlite:///%(here)s/app.db'
  fsblobstorage_path: '%(here)s/blobstorage'
  {% if cookiecutter.project_type == "morpfw" %} 
  authn_policy: morpfw.authn.useridparam:AuthnPolicy
  {% elif cookiecutter.project_type == "morpcc" %} 
  authn_policy: morpcc.app:AuthnPolicy
  {% endif %}
  
security:
  jwt:
    master_secret: secret

{% if cookiecutter.project_type == "morpcc" %} 
 
beaker_session:
  session.cookie_expires: True
{% endif %}

