language: python
dist: xenial
sudo: required
python:
  - 3.6
  - 3.7
env:
  - LIBVERSION=master
  - LIBVERSION=2.7.0
  - LIBVERSION=2.6.0
before_script:
  - pip install flake8
  - pip install flake8-builtins
  - pip install flake8-import-order
  - pip install flake8-quotes
  - pip install pep8-naming
  - pip install tabulate
  - pip install cmp_version
  - pip install version || true  # for the case it learns python3
  - wget -qO- https://github.com/repology/libversion/archive/$LIBVERSION.tar.gz | tar -xzf- && ( cd libversion-$LIBVERSION && cmake . && make && sudo make install && sudo ldconfig )
script:
  - flake8
  - python setup.py test
  - python setup.py install
  - cd demos
  - ${PYTHON} ./compare.py
  - ${PYTHON} ./benchmark.py
