pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: brewblox

steps:

- bash: |
    export TRAVIS_BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    export GIT_TAG=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    echo "##vso[task.setvariable variable=branch]$TRAVIS_BRANCH"
    echo "##vso[task.setvariable variable=tag]$GIT_TAG"
  name: setvarStep
  displayName: export build variables

- bash: |
    echo $(setvarStep.branch)
    echo $(setvarStep.tag)
  displayName: check vars

- bash: |
    echo $(setvarStep.branch)
    echo $(setvarStep.tag)
  displayName: check condition
  condition: and(succeeded(), variables['setvarStep.branch'])

- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.7'
    architecture: 'x64'

- bash: |
    pip install pipenv
    pipenv sync --dev
    pipenv run pytest
  displayName: Run Pytest

# - bash: >
#     bbt-localbuild
#     --arch amd arm
#     --tags newest-tag $(git describe --tags)
#     --push
#   displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits
#   condition: and(succeeded(), )

- bash: >
    pipenv run
    bbt-localbuild
    --arch amd arm
    --branch-tag
  displayName: Deploy branch to Docker Hub on any push to the GitHub repository
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), variables['setvarStep.branch'])

