
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "e2820e255bd39af96c4d67a48638f42d5a83eb27",
 "version": "0.15.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
