from typing import Tuple, Set, Iterable, List

class IAssemblyRestrictedObject:
    def Editable (self) -> bool: ...
class Notification:
    def __init__(self, allowedAssemblies : Iterable(Assembly)): ...
    def __init__(self): ...
    @property
    def DateUpdated (self) -> DateTime: ...
    @property
    def AllowedAssemblies (self) -> ICollection: ...
    @property
    def MetadataCopy (self) -> IDictionary: ...
    @property
    def ButtonClicked (self) -> Action: ...
    @ButtonClicked.setter
    def ButtonClicked (self, value : Action): ...
    @property
    def Item (self, key : str) -> str: ...
    @Item.setter
    def Item (self, key : str, value : str): ...
    @property
    def Title (self) -> str: ...
    @Title.setter
    def Title (self, value : str): ...
    @property
    def Description (self) -> str: ...
    @Description.setter
    def Description (self, value : str): ...
    @property
    def Message (self) -> str: ...
    @Message.setter
    def Message (self, value : str): ...
    @property
    def SeverityLevel (self) -> Severity: ...
    @SeverityLevel.setter
    def SeverityLevel (self, value : Severity): ...
    @property
    def CancelButtonTitle (self) -> str: ...
    @CancelButtonTitle.setter
    def CancelButtonTitle (self, value : str): ...
    @property
    def ConfirmButtonTitle (self) -> str: ...
    @ConfirmButtonTitle.setter
    def ConfirmButtonTitle (self, value : str): ...
    @property
    def AlternateButtonTitle (self) -> str: ...
    @AlternateButtonTitle.setter
    def AlternateButtonTitle (self, value : str): ...
    @property
    def ShowEventId (self) -> Nullable: ...
    def ExecuteAssemblyProtectedCode (action : Action): ...
    def ExecuteAssemblyProtectedCode (func : Func) -> TResult: ...
    def ShowModal (self): ...
    def HideModal (self): ...
    def RemoveMetadata (self, key : str) -> bool: ...
    def ToString (self) -> str: ...
    def Editable (self) -> bool: ...
    def add_PropertyChanged (self, value : PropertyChangedEventHandler): ...
    def remove_PropertyChanged (self, value : PropertyChangedEventHandler): ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class ButtonType:
    CancelOrClose = 0
    Confirm = 1
    Alternate = 2
class NotificationButtonClickedArgs:
    def __init__(self, notification : Notification, buttonClicked : ButtonType): ...
    @property
    def Notification (self) -> Notification: ...
    @property
    def ButtonClicked (self) -> ButtonType: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class NotificationCenter:
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Severity:
    Debug = 0
    Info = 1
    Warning = 2
    Serious = 3
    Critical = 4
