[tool.poetry]
name = "red-connector-httpdirfs"
version = "0.1"
authors = ["Bruno Schilling <s0555131@htw-berlin.de>", "Christoph Jansen <Christoph.Jansen@htw-berlin.de>"]
license = "AGPL-3.0"
readme = "README.md"
repository = "https://github.com/curious-containers/red-connector-httpdirfs"
homepage = "https://www.curious-containers.cc/"
description = "RED Connector HTTP is part of the Curious Containers project."

[tool.poetry.dependencies]
python = "^3.4"
jsonschema = "^2.6"
cc-connector-cli = "^0.3.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
red-connector-httpdirfs = 'red_connector_httpdirfs.main:main'
