
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-23T16:53:38+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f7cea3e20a6aeabaa1e5e1f2cae2252f32a5b052",
 "version": "0.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
