# coding: utf-8

"""
    (C) Copyright 2018-2019 Hewlett Packard Enterprise Development LP

    Reporting

    unused  # noqa: E501

    Component version: 2.0.13-SNAPSHOT
"""


import pprint
import re  # noqa: F401

import six


class SSLSocketFactory(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'supported_cipher_suites': 'list[str]',
        'default_cipher_suites': 'list[str]'
    }

    attribute_map = {
        'supported_cipher_suites': 'supportedCipherSuites',
        'default_cipher_suites': 'defaultCipherSuites'
    }

    def __init__(self, supported_cipher_suites=None, default_cipher_suites=None):  # noqa: E501
        """SSLSocketFactory - a model defined in Swagger"""  # noqa: E501

        self._supported_cipher_suites = None
        self._default_cipher_suites = None
        self.discriminator = None

        if supported_cipher_suites is not None:
            self.supported_cipher_suites = supported_cipher_suites
        if default_cipher_suites is not None:
            self.default_cipher_suites = default_cipher_suites

    @property
    def supported_cipher_suites(self):
        """Gets the supported_cipher_suites of this SSLSocketFactory.  # noqa: E501


        :return: The supported_cipher_suites of this SSLSocketFactory.  # noqa: E501
        :rtype: list[str]
        """
        return self._supported_cipher_suites

    @supported_cipher_suites.setter
    def supported_cipher_suites(self, supported_cipher_suites):
        """Sets the supported_cipher_suites of this SSLSocketFactory.


        :param supported_cipher_suites: The supported_cipher_suites of this SSLSocketFactory.  # noqa: E501
        :type: list[str]
        """

        self._supported_cipher_suites = supported_cipher_suites

    @property
    def default_cipher_suites(self):
        """Gets the default_cipher_suites of this SSLSocketFactory.  # noqa: E501


        :return: The default_cipher_suites of this SSLSocketFactory.  # noqa: E501
        :rtype: list[str]
        """
        return self._default_cipher_suites

    @default_cipher_suites.setter
    def default_cipher_suites(self, default_cipher_suites):
        """Sets the default_cipher_suites of this SSLSocketFactory.


        :param default_cipher_suites: The default_cipher_suites of this SSLSocketFactory.  # noqa: E501
        :type: list[str]
        """

        self._default_cipher_suites = default_cipher_suites

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SSLSocketFactory, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SSLSocketFactory):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
