pool:
  vmImage: 'Ubuntu-16.04'

variables:
  - group: brewblox

steps:

# Exports values as environment values, and as pipeline variables
- bash: |
    export TRAVIS_BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    export GIT_TAG=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    echo "##vso[task.setvariable variable=brewblox.branch]$TRAVIS_BRANCH"
    echo "##vso[task.setvariable variable=brewblox.tag]$GIT_TAG"
  displayName: export build variables

# - bash: |
#     echo $(travis.branch)
#     echo $(git.tag)
#   displayName: check vars

# - bash: |
#     echo $(travis.branch)
#     echo $(git.tag)
#   displayName: check condition
#   condition: and(succeeded(), variables['travis.branch'])

# - bash: |
#     echo $(git.tag)
#   displayName: check false condition
#   condition: and(succeeded(), variables['git.tag'])

- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.7'
    architecture: 'x64'

- bash: |
    pip install pipenv
    pipenv sync --dev
    pipenv run pytest
  displayName: Run Pytest

- bash: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  displayName: Docker login

- bash: >
    pipenv run
    bbt-localbuild
    --arch amd arm
    --tags newest-tag $(git.tag)
    --push
  condition: and(succeeded(), variables['brewblox.tag'])
  displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits

- bash: >
    pipenv run
    bbt-localbuild
    --arch amd arm
    --branch-tag
    --push
  condition: and(succeeded(), variables['brewblox.branch'], not(variables['brewblox.tag']))
  displayName: Deploy branch to Docker Hub on any push to the GitHub repository
