[tool.poetry]
name = "fast-rpc"
version = "0.1.0"
description = "Pure python implementation of binary FastRPC format de/serialisation"
authors = ["Ken Mijime <kenaco666@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
wheel = "^0.33.1"
pytest = "^4.3"
ipython = "^7.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
