- name: ensure libsemanage-python is installed
  package:
    name: libsemanage-python
    state: present
  retries: 2
  register: install_libsemanage
  until: install_libsemanage is success

- name: enable selinux overrides
  seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  with_items:
    - httpd_can_network_connect
    - httpd_can_network_connect_db
    - httpd_can_sendmail
