image: python:3-alpine

stages:
  - tests
  - deploy

#########################################
##### Testing for single components #####
#########################################

unit:
    stage: tests
    before_script:
        - python3 -m pip install --user requests
    script:
        - python3 -m unittest discover tests

#########################################
###### Testing of the whole system ######
#########################################

linter:
    stage: tests
    before_script:
      - python3 -m pip install --user requests prospector
    script:
      - echo "Running linter for project"
      - python3 -m prospector sbrowser


#########################################
############# Deployment ################
#########################################

pypi:
  stage: deploy
  before_script:
    - python3 -m pip install --user --upgrade twine setuptools wheel
    - apk add git
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/*
  only:
    - tags
    - triggers
