---

- include: setup.yml

- hosts: '*'
  vars:
    path: ~

  tasks:
  - name: Create home directory
    tags: setup
    file: path='{{ path }}' state=directory

  - name: Upload new docker-compose file at destination path
    tags: update
    copy:
      src: '{{ compose }}'
      dest: '{{ path }}/docker-compose.yml'

  - name: Any .env file to upload ?
    tags: update
    stat: path=.env
    delegate_to: localhost
    register: env_stat

  - name: Upload .env file if any
    tags: update
    when: env_stat.stat.exists
    copy:
      src: .env
      dest: '{{ path }}/.env'

  - name: docker-compose pull
    tags: update
    async: 300
    poll: 0
    shell: docker-compose pull
    register: compose_pull
    args:
      chdir: '{{ path }}'
      executable: /bin/bash

  - name: Create filesystem directories for each service
    compose_directories: services='{{ services }}' path='{{ path }}'

  - name: Compose wait for pull complete
    async_status:
      jid: "{{ compose_pull.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 30

  - name: Restart compose services
    shell: |
      docker-compose stop
      docker-compose up -d --remove-orphans
    args:
      chdir: '{{ path }}'
      executable: /bin/bash
