# Permissions ###
ADMIN = 'ADMIN'
SYS_ADMIN = 'SYS_ADMIN'
LICENSED_USER = 'LICENSED_USER'
PROJECT_ADMIN = 'PROJECT_ADMIN'
PROJECT_CREATE = 'PROJECT_CREATE'
PROJECT_READ = 'PROJECT_READ'
PROJECT_VIEW = 'PROJECT_VIEW'
APP_ADMIN = 'APP_ADMIN'
APP_WRITE = 'APP_WRITE'
APP_READ = 'APP_READ'

BITBUCKET_PERMISSIONS = (
    (ADMIN, 'ADMIN'),
    (SYS_ADMIN, 'SYS_ADMIN'),
    (LICENSED_USER, 'LICENSED_USER'),

    (PROJECT_ADMIN, 'PROJECT_ADMIN'),
    (PROJECT_CREATE, 'PROJECT_CREATE'),
    (PROJECT_READ, 'PROJECT_READ'),
    (PROJECT_VIEW, 'PROJECT_VIEW'),

    (APP_ADMIN, 'REPO_ADMIN'),
    (APP_WRITE, 'REPO_WRITE'),
    (APP_READ, 'REPO_READ')
)

BITBUCKET_PROJECT_PERMISSIONS = (
    (PROJECT_ADMIN, 'PROJECT_ADMIN'), (PROJECT_CREATE, 'PROJECT_CREATE'),
    (PROJECT_READ, 'PROJECT_READ'), (PROJECT_VIEW, 'PROJECT_VIEW'),
)

BITBUCKET_APP_PERMISSIONS = (
    (APP_ADMIN, 'REPO_ADMIN'), (APP_WRITE, 'REPO_WRITE'), (APP_READ, 'REPO_READ'),
)
