# Generated by Django 2.1.1 on 2019-02-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0015_auto_20190207_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Company'),
        ),
    ]
