# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugtrack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='depends_on',
            field=models.CharField(blank=True, default=b'', max_length=256, null=True),
        ),
    ]
