# Version file autogenerated by the build process
version = '0.6.3rc1'
build = '283'
vcs_info = 'Git SHA1 7cb08e09 committed on 2019-02-19'

if __name__ == '__main__':
    print('KSCONF_VERSION="0.6.3rc1"\nKSCONF_BUILD="283"\nKSCONF_VCS_INFO="Git SHA1 7cb08e09 committed on 2019-02-19"')
