#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['rco_dl']

package_data = \
{'': ['*']}

install_requires = \
['aiofiles==0.4.*', 'aiohttp==3.5.*', 'cfscrape']

entry_points = \
{'console_scripts': ['rco_dl = rco_dl:main']}

setup(name='rco_dl',
      version='1.3',
      description='ReadComicOnline.to Downloader',
      author='dyeray',
      author_email='dyeray@gmail.com',
      url='https://github.com/dyeray/readcomiconline-downloader/',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      entry_points=entry_points,
      python_requires='>=3',
     )
