[tool.poetry]
name = "flake8-plugin-utils"
version = "0.2.0"
description = "Package provide base classes and utils for flake8 plugin writing"
authors = ["Afonasev Evgeniy <ea.afonasev@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/afonasev/flake8-plugin-utils"
homepage = "https://pypi.org/project/flake8-plugin-utils"
keywords = ['flake8', 'plugin', 'utils']

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
flake8 = "^3.7"
flake8-builtins = "^1.4"
flake8-comprehensions = "^1.4"
flake8-eradicate = "^0.2.0"
flake8-isort = "^2.6"
flake8-logging-format = "^0.6.0"
flake8-pie = "^0.1.0"
flake8-pytest = "^1.3"
flake8-quotes = "^1.0"
mypy = "^0.660.0"
pep8-naming = "^0.8.0"
pylint = "^2.2"
pytest = "^3.0"
pytest-cov = "^2.6"
pytest-mock = "^1.10"
unify = "^0.4.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
