apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    nodePort: 32001
  - name: http
    port: 32000
    targetPort: 32000
    nodePort: 32000
  selector:
    app: api
