[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "pomw"
version = "0.0.7"
description = "The Pomodoro Technique using TaskWarrior and TimeWarrior"
authors = [ "Tjaart van der Walt <tjaart@tjaart.org>",]
license = "GPL-3.0-or-later"

[tool.poetry.dependencies]
python = "^3.7"
argcomplete = "^1.9"
python-dateutil = "^2.7"
taskw = "^1.2"
timew = "^0.0.18"
unijson = "^1.0"
urwid = "^2.0"
semver = "^2.8"

[tool.poetry.dev-dependencies]
pytest = "^4.3"
toml = "^0.10.0"
pycodestyle = "^2.5"
pytest-cov = "^2.6"
tox = "^3.7"
jedi = "^0.13.3"
