from typing import Tuple, Set, Iterable, List

class FieldDictionary:
    def Set (self, key : str, value : Set(Byte), changeContext : ChangeContexts): ...
    def SetTag (self, key : str, tag : Object) -> bool: ...
    def TryGetTag (self, key : str) -> Tuple(bool, Object): ...
    def TryGetValue (self, key : str) -> Tuple(bool, T): ...
    def TryGetValue (self, key : str) -> Tuple(bool, str): ...
    def TryGetValue (self, key : str) -> Tuple(bool, bool): ...
    def TryGetValue (self, key : str) -> Tuple(bool, int): ...
    def TryGetValue (self, key : str) -> Tuple(bool, float): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Single): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Color4f): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Color): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Vector2d): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Vector3d): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Point2d): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Point3d): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Point4d): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Guid): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Transform): ...
    def TryGetValue (self, key : str) -> Tuple(bool, DateTime): ...
    def TryGetValue (self, key : str) -> Tuple(bool, Set(Byte)): ...
    def GetEnumerator (self) -> IEnumerator: ...
    def ContainsField (self, fieldName : str) -> bool: ...
    def GetField (self, fieldName : str) -> Field: ...
    def RemoveField (self, fieldName : str): ...
    def Add (self, key : str, value : str) -> StringField: ...
    def Add (self, key : str, value : str, prompt : str) -> StringField: ...
    def AddTextured (self, key : str, value : str, prompt : str) -> StringField: ...
    def Add (self, key : str, value : bool) -> BoolField: ...
    def Add (self, key : str, value : bool, prompt : str) -> BoolField: ...
    def AddTextured (self, key : str, value : bool, prompt : str) -> BoolField: ...
    def Add (self, key : str, value : int) -> IntField: ...
    def Add (self, key : str, value : int, prompt : str) -> IntField: ...
    def AddTextured (self, key : str, value : int, prompt : str) -> IntField: ...
    def Add (self, key : str, value : Single) -> FloatField: ...
    def Add (self, key : str, value : Single, prompt : str) -> FloatField: ...
    def AddTextured (self, key : str, value : Single, prompt : str) -> FloatField: ...
    def Add (self, key : str, value : float) -> DoubleField: ...
    def Add (self, key : str, value : float, prompt : str) -> DoubleField: ...
    def AddTextured (self, key : str, value : float, prompt : str) -> DoubleField: ...
    def Add (self, key : str, value : Color4f) -> Color4fField: ...
    def Add (self, key : str, value : Color4f, prompt : str) -> Color4fField: ...
    def AddTextured (self, key : str, value : Color4f, prompt : str) -> Color4fField: ...
    def Add (self, key : str, value : Color) -> Color4fField: ...
    def Add (self, key : str, value : Color, prompt : str) -> Color4fField: ...
    def AddTextured (self, key : str, value : Color, prompt : str) -> Color4fField: ...
    def Add (self, key : str, value : Vector2d) -> Vector2dField: ...
    def Add (self, key : str, value : Vector2d, prompt : str) -> Vector2dField: ...
    def AddTextured (self, key : str, value : Vector2d, prompt : str) -> Vector2dField: ...
    def Add (self, key : str, value : Vector3d) -> Vector3dField: ...
    def Add (self, key : str, value : Vector3d, prompt : str) -> Vector3dField: ...
    def AddTextured (self, key : str, value : Vector3d, prompt : str) -> Vector3dField: ...
    def Add (self, key : str, value : Point2d) -> Point2dField: ...
    def Add (self, key : str, value : Point2d, prompt : str) -> Point2dField: ...
    def AddTextured (self, key : str, value : Point2d, prompt : str) -> Point2dField: ...
    def Add (self, key : str, value : Point3d) -> Point3dField: ...
    def Add (self, key : str, value : Point3d, prompt : str) -> Point3dField: ...
    def AddTextured (self, key : str, value : Point3d, prompt : str) -> Point3dField: ...
    def Add (self, key : str, value : Point4d) -> Point4dField: ...
    def Add (self, key : str, value : Point4d, prompt : str) -> Point4dField: ...
    def AddTextured (self, key : str, value : Point4d, prompt : str) -> Point4dField: ...
    def Add (self, key : str, value : Guid) -> GuidField: ...
    def Add (self, key : str, value : Guid, prompt : str) -> GuidField: ...
    def AddTextured (self, key : str, value : Guid, prompt : str) -> GuidField: ...
    def Add (self, key : str, value : Transform) -> TransformField: ...
    def Add (self, key : str, value : Transform, prompt : str) -> TransformField: ...
    def AddTextured (self, key : str, value : Transform, prompt : str) -> TransformField: ...
    def Add (self, key : str, value : DateTime) -> DateTimeField: ...
    def Add (self, key : str, value : DateTime, prompt : str) -> DateTimeField: ...
    def AddTextured (self, key : str, value : DateTime, prompt : str) -> DateTimeField: ...
    def Add (self, key : str, value : Set(Byte)) -> ByteArrayField: ...
    def Set (self, key : str, value : str): ...
    def Set (self, key : str, value : str, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : bool): ...
    def Set (self, key : str, value : bool, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : int): ...
    def Set (self, key : str, value : int, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Single): ...
    def Set (self, key : str, value : Single, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : float): ...
    def Set (self, key : str, value : float, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Color4f): ...
    def Set (self, key : str, value : Color4f, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Color): ...
    def Set (self, key : str, value : Color, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Vector2d): ...
    def Set (self, key : str, value : Vector2d, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Vector3d): ...
    def Set (self, key : str, value : Vector3d, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Point2d): ...
    def Set (self, key : str, value : Point2d, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Point3d): ...
    def Set (self, key : str, value : Point3d, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Point4d): ...
    def Set (self, key : str, value : Point4d, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Guid): ...
    def Set (self, key : str, value : Guid, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Transform): ...
    def Set (self, key : str, value : Transform, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : DateTime): ...
    def Set (self, key : str, value : DateTime, changeContext : ChangeContexts): ...
    def Set (self, key : str, value : Set(Byte)): ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Field:
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def ValueAsObject (self) -> Object: ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class StringField:
    @property
    def Value (self) -> str: ...
    @Value.setter
    def Value (self, value : str): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class BoolField:
    @property
    def Value (self) -> bool: ...
    @Value.setter
    def Value (self, value : bool): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class IntField:
    @property
    def Value (self) -> int: ...
    @Value.setter
    def Value (self, value : int): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class FloatField:
    @property
    def Value (self) -> Single: ...
    @Value.setter
    def Value (self, value : Single): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class DoubleField:
    @property
    def Value (self) -> float: ...
    @Value.setter
    def Value (self, value : float): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Color4fField:
    @property
    def Value (self) -> Color4f: ...
    @Value.setter
    def Value (self, value : Color4f): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def SystemColorValue (self) -> Color: ...
    @SystemColorValue.setter
    def SystemColorValue (self, value : Color): ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Vector2dField:
    @property
    def Value (self) -> Vector2d: ...
    @Value.setter
    def Value (self, value : Vector2d): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Vector3dField:
    @property
    def Value (self) -> Vector3d: ...
    @Value.setter
    def Value (self, value : Vector3d): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Point2dField:
    @property
    def Value (self) -> Point2d: ...
    @Value.setter
    def Value (self, value : Point2d): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Point3dField:
    @property
    def Value (self) -> Point3d: ...
    @Value.setter
    def Value (self, value : Point3d): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class Point4dField:
    @property
    def Value (self) -> Point4d: ...
    @Value.setter
    def Value (self, value : Point4d): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class GuidField:
    @property
    def Value (self) -> Guid: ...
    @Value.setter
    def Value (self, value : Guid): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class TransformField:
    @property
    def Value (self) -> Transform: ...
    @Value.setter
    def Value (self, value : Transform): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class DateTimeField:
    @property
    def Value (self) -> DateTime: ...
    @Value.setter
    def Value (self, value : DateTime): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
class ByteArrayField:
    @property
    def Value (self) -> Set(Byte): ...
    @Value.setter
    def Value (self, value : Set(Byte)): ...
    def ValueAsObject (self) -> Object: ...
    @property
    def Name (self) -> str: ...
    @property
    def Key (self) -> str: ...
    @property
    def Tag (self) -> Object: ...
    @Tag.setter
    def Tag (self, value : Object): ...
    def GetValue (self) -> T: ...
    def ToString (self) -> str: ...
    def Equals (self, obj : Object) -> bool: ...
    def GetHashCode (self) -> int: ...
    def GetType (self) -> Type: ...
