# coding: utf-8

"""
    (C) Copyright 2018-2019 Hewlett Packard Enterprise Development LP

    Reporting

    unused  # noqa: E501

    Component version: 2.0.13-SNAPSHOT
"""


import pprint
import re  # noqa: F401

import six


class TrustedCluster(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'name': 'str',
        'vif': 'str',
        'trusted_hosts': 'list[TrustedHost]'
    }

    attribute_map = {
        'uuid': 'uuid',
        'name': 'name',
        'vif': 'vif',
        'trusted_hosts': 'trustedHosts'
    }

    def __init__(self, uuid=None, name=None, vif=None, trusted_hosts=None):  # noqa: E501
        """TrustedCluster - a model defined in Swagger"""  # noqa: E501

        self._uuid = None
        self._name = None
        self._vif = None
        self._trusted_hosts = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if vif is not None:
            self.vif = vif
        if trusted_hosts is not None:
            self.trusted_hosts = trusted_hosts

    @property
    def uuid(self):
        """Gets the uuid of this TrustedCluster.  # noqa: E501


        :return: The uuid of this TrustedCluster.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this TrustedCluster.


        :param uuid: The uuid of this TrustedCluster.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this TrustedCluster.  # noqa: E501


        :return: The name of this TrustedCluster.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TrustedCluster.


        :param name: The name of this TrustedCluster.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def vif(self):
        """Gets the vif of this TrustedCluster.  # noqa: E501


        :return: The vif of this TrustedCluster.  # noqa: E501
        :rtype: str
        """
        return self._vif

    @vif.setter
    def vif(self, vif):
        """Sets the vif of this TrustedCluster.


        :param vif: The vif of this TrustedCluster.  # noqa: E501
        :type: str
        """

        self._vif = vif

    @property
    def trusted_hosts(self):
        """Gets the trusted_hosts of this TrustedCluster.  # noqa: E501


        :return: The trusted_hosts of this TrustedCluster.  # noqa: E501
        :rtype: list[TrustedHost]
        """
        return self._trusted_hosts

    @trusted_hosts.setter
    def trusted_hosts(self, trusted_hosts):
        """Sets the trusted_hosts of this TrustedCluster.


        :param trusted_hosts: The trusted_hosts of this TrustedCluster.  # noqa: E501
        :type: list[TrustedHost]
        """

        self._trusted_hosts = trusted_hosts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TrustedCluster, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TrustedCluster):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
