
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-02-13T14:36:13-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e55ba2519ac82ebed155ebf1f64216b629ab6b4e",
 "version": "0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
