sudo: false
dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
env:
  - DJANGO="2.0"
  - DJANGO="2.1"
  - DJANGO="master"
matrix:
  exclude:
    - env: DJANGO="master"
      python: "3.5"
  allow_failures:
    - env: DJANGO="master"
after_success: codecov
install: pip install tox-travis codecov
script: tox
