nginx_capable: true
httpd_capable: true
## set some defaults with the expectation that they will be set in/from calling role
# canonical name for service
service_name: "{{ hostvars[inventory_hostname]['ansible_host'] | default(inventory_hostname) }}"

## nginx core configuration defaults
nginx_error_level: "warn"
nginx_worker_processes: 1
nginx_gzip_status: "on"
# Increase upload limits to allow jenkins plugin uploads
nginx_max_body_size: 100M
nginx_send_timeout: 120s

## variables unset by default
httpd_no_error_pages: false
https_enabled: false
# If httpd_keytab_file, httpd_ssl_key_file and httpd_ssl_crt_file
# are already present on the remote Jenkins master being configured by cinch,
# set the following variable to true to copy the files from the filesystem
# of the remote host rather than from the system running Ansible
httpd_ssl_keytab_files_remote_src: false
# local path to use as source for keytab
#httpd_keytab_file: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
# Local path to the SSL certificate to use in configuring HTTPS. Can be full or relative
# to the path from where the main playbook is run. This can be overriden if you want
# secure access to Jenkins using your own SSL certificate. By default, a self signed
# certificate will be created and used.
#httpd_ssl_key_file: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
# Local path to the SSL private key in crt or pem format. For more details see comment above.
# When using own SSL certificates, you need to override either this variable
#httpd_ssl_crt_file: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
# Local path to the SSL private key in PEM format. For more details see comment above.
#httpd_ssl_pem_file: "/THIS/FILE/PROBABLY/DOESNT/EXIST"
# location and CN settings for the self signed certificate
ssl_self_signed_string: "/C=US/ST=New York/L=New York City/O=My Department/CN={{ service_name }}"
# whether to use a speedy method to generate Diffie Hellman parameters
ssl_fast_dh: false
nginx_ssl_ca_line: "#ssl_client_certificate /path/to/ca/file;"

httpd_keytab_line: "auth_gss_keytab /etc/nginx/conf.d/httpd.keytab;"
