language: python
python:
  - '3.6'
install:
  - python setup.py install
  - pip install -I -r requirements/test.txt
script:
  - pytest --cov=protean_sqlalchemy --cov-config .coveragerc tests
after_success:
  - pip install codecov
  - codecov
