# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 11:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TUserAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='ACCESS_Token', null=True, verbose_name='ACCESS_Token')),
                ('recheck_after', models.DateTimeField(default=datetime.datetime.now, help_text='\u8d85\u8fc7\u8fd9\u4e2a\u65f6\u95f4\uff0c\u5ba2\u6237\u7aef\u8fd8\u5e26\u8fd9\u4e2atoken\u7684\u8bdd\uff0c\u91cd\u65b0\u5230\u6388\u6743\u670d\u52a1\u5668\u6821\u9a8c', verbose_name='\u91cd\u65b0\u9a8c\u8bc1\u65f6\u95f4')),
                ('user', models.ForeignKey(help_text='\u5173\u8054\u7684\u7528\u6237', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7684\u7528\u6237')),
            ],
            options={
                'db_table': 't_user_access_token_cache',
                'verbose_name': '\u7528\u6237AccessToken\u7f13\u5b58',
                'verbose_name_plural': '\u7528\u6237AccessToken\u7f13\u5b58',
            },
        ),
        migrations.CreateModel(
            name='TUserExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='\u7528\u6237\u7684\u663e\u793a\u540d', max_length=200, null=True, verbose_name='\u7528\u6237\u7684\u663e\u793a\u540d')),
                ('phone_number', models.CharField(help_text='\u7528\u6237\u624b\u673a\u53f7', max_length=16, null=True, verbose_name='\u7528\u6237\u624b\u673a\u53f7')),
                ('access_token', models.CharField(help_text='\u6388\u6743\u670d\u52a1\u5668\u7684\u63a5\u5165token', max_length=50, null=True, verbose_name='\u63a5\u5165token')),
                ('expires_in', models.PositiveIntegerField(default=0, help_text='ACCESS TOKEN\u7684\u8d85\u65f6\u65f6\u95f4', verbose_name='\u8d85\u65f6\u65f6\u95f4')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='ACCESS TOKEN\u7684\u5f00\u59cb\u8ba1\u65f6\u65f6\u95f4', verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('token_type', models.CharField(help_text='TOKEN\u7c7b\u578b', max_length=20, null=True, verbose_name='TOKEN\u7c7b\u578b')),
                ('scope', models.CharField(help_text='\u6743\u9650\u8303\u56f4', max_length=50, null=True, verbose_name='\u6743\u9650\u8303\u56f4')),
                ('refresh_token', models.CharField(help_text='\u53ef\u4ee5\u7528\u5b83\u6765\u5237\u65b0TOKEN', max_length=50, null=True, verbose_name='REFRESH TOKEN')),
                ('remote_privileges', models.TextField(help_text='Privileges on AuthServer Return', null=True, verbose_name='Privileges on AuthServer Return')),
                ('local_privileges', models.TextField(help_text='Privileges on local Server', null=True, verbose_name='Privileges on local Server')),
                ('user', models.OneToOneField(help_text='\u5173\u8054\u7684\u7528\u6237', on_delete=django.db.models.deletion.CASCADE, related_name='extra', to=settings.AUTH_USER_MODEL, verbose_name='\u5173\u8054\u7684\u7528\u6237')),
            ],
            options={
                'db_table': 't_oauth_user_extra',
                'verbose_name': 'OAuthUser',
                'verbose_name_plural': 'OAuthUser',
            },
        ),
    ]
