# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/proto/net/MastershipRoleProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/proto/net/MastershipRoleProto.proto',
  package='net',
  syntax='proto3',
  serialized_options=_b('\n\037org.onosproject.grpc.net.models'),
  serialized_pb=_b('\n,protobuf/proto/net/MastershipRoleProto.proto\x12\x03net*8\n\x13MastershipRoleProto\x12\x08\n\x04NONE\x10\x00\x12\n\n\x06MASTER\x10\x01\x12\x0b\n\x07STANDBY\x10\x02\x42!\n\x1forg.onosproject.grpc.net.modelsb\x06proto3')
)

_MASTERSHIPROLEPROTO = _descriptor.EnumDescriptor(
  name='MastershipRoleProto',
  full_name='net.MastershipRoleProto',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MASTER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STANDBY', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=53,
  serialized_end=109,
)
_sym_db.RegisterEnumDescriptor(_MASTERSHIPROLEPROTO)

MastershipRoleProto = enum_type_wrapper.EnumTypeWrapper(_MASTERSHIPROLEPROTO)
NONE = 0
MASTER = 1
STANDBY = 2


DESCRIPTOR.enum_types_by_name['MastershipRoleProto'] = _MASTERSHIPROLEPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
