image: python:3-alpine

stages:
  - formatting
  - unittest
  - totaltest
  - deploy

before_script:
  - python3 -m pip install -r requirements.txt

#########################################
####### Make static code analysis #######
#########################################

linter:
  stage: formatting
  script:
    - python3 -m pip install pylint
    - echo "Running linter for project"
    - python3 -m pylint metadata_expander *.py

docu:
  stage: formatting
  script:
    - python3 -m pip install --user pydocstyle pep257
    - echo "Checking for correct documentation"
    - python3 -m pep257 .
    - python3 -m pydocstyle .


#########################################
##### Testing for single components #####
#########################################

unit:
  stage: unittest
  script:
    - python3 -m pip install pytest-cov
    - echo "Running unit tests for all python test cases"
    - python3 -m pytest -v --color=yes --cov .


#########################################
###### Testing of the whole system ######
#########################################

runtest:
  stage: totaltest
  script:
    - echo "Running a test of the whole system"
    - python3 expander.py -s "Using Genetic Algorithm Approach to Reduce Register File Pressure during Instruction Scheduling"
    - python3 expander.py 10.1109/SAMOS.2017.8344626


#########################################
############# Deployment ################
#########################################

pypi:
  stage: deploy
  before_script:
    - apk add git
    - python3 -m pip install twine setuptools wheel
  script:
    - python3 setup.py sdist bdist_wheel
    - python3 -m twine upload dist/*
  only:
    - tags
    - triggers
