---
  - name: Install Python Depedencies on Red Hat (like) systems
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ avocado_python_rpm_packages }}"
    when: ansible_distribution_file_variety == "RedHat"
